KEY_USE_ABILITY = L_TRIG
KEY_SELECT_ABILITY_LEFT = L_JPAD
KEY_SELECT_ABILITY_RIGHT = R_JPAD
KEY_CHANGE_ABILITY_MODE = Y_BUTTON
KEY_CHANGE_ABILITY_LEVEL_UP = U_JPAD
KEY_CHANGE_ABILITY_LEVEL_DOWN = D_JPAD
KEY_USE_CHANT = X_BUTTON
