extern const GeoLayout arena_area_1_geo[];
extern const GeoLayout arena_area_1[];
extern const Collision arena_area_1_collision[];
extern const MacroObject arena_area_1_macro_objs[];
extern Lights1 arena_dl_f3dlite_material_005_lights;
extern u8 arena_dl_vulkan_ci8[];
extern u8 arena_dl_vulkan_pal_rgba16[];
extern u8 arena_dl_lava_ci8[];
extern u8 arena_dl_lava_pal_rgba16[];
extern u8 arena_dl_brisk_i8[];
extern u8 arena_dl_woodfloor_ci8[];
extern u8 arena_dl_woodfloor_pal_rgba16[];
extern Vtx arena_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx arena_dl_Cube_mesh_layer_1_vtx_0[26];
extern Gfx arena_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx arena_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx arena_dl_Cube_001_mesh_layer_1_vtx_0[13];
extern Gfx arena_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx arena_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx arena_dl_Cube_002_mesh_layer_1_vtx_0[1512];
extern Gfx arena_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx arena_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx arena_dl_Plane_mesh_layer_1_vtx_0[123];
extern Gfx arena_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx arena_dl_Plane_mesh_layer_1_vtx_1[253];
extern Gfx arena_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx arena_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx arena_dl_Plane_mesh_layer_5_vtx_0[128];
extern Gfx arena_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_arena_dl_f3dlite_material[];
extern Gfx mat_revert_arena_dl_f3dlite_material[];
extern Gfx mat_arena_dl_f3dlite_material_001[];
extern Gfx mat_revert_arena_dl_f3dlite_material_001[];
extern Gfx mat_arena_dl_f3dlite_material_002[];
extern Gfx mat_revert_arena_dl_f3dlite_material_002[];
extern Gfx mat_arena_dl_f3dlite_material_004[];
extern Gfx mat_revert_arena_dl_f3dlite_material_004[];
extern Gfx mat_arena_dl_f3dlite_material_005[];
extern Gfx mat_revert_arena_dl_f3dlite_material_005[];
extern Gfx arena_dl_Cube_mesh_layer_1[];
extern Gfx arena_dl_Cube_001_mesh_layer_1[];
extern Gfx arena_dl_Cube_002_mesh_layer_1[];
extern Gfx arena_dl_Plane_mesh_layer_1[];
extern Gfx arena_dl_Plane_mesh_layer_5[];
